name: jsonify
description: A Dart library to access the webstorage API like an (almost) full JSON client-side storage
version: 0.1.0
homepage: https://github.com/nkratzke/jsonify
author: Nane Kratzke <nane.kratzke@fh-luebeck.de>

environment:
  sdk: '>=1.20.1 <2.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^0.12.0
